# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.tool_product_settings import ToolProductSettings  # noqa: E501
from djclient.rest import ApiException


class TestToolProductSettings(unittest.TestCase):
    """ToolProductSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToolProductSettings(self):
        """Test ToolProductSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.tool_product_settings.ToolProductSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
