# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.test_type import TestType  # noqa: E501
from djclient.rest import ApiException


class TestTestType(unittest.TestCase):
    """TestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestType(self):
        """Test TestType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.test_type.TestType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
