# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.test_create import TestCreate  # noqa: E501
from djclient.rest import ApiException


class TestTestCreate(unittest.TestCase):
    """TestCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCreate(self):
        """Test TestCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.test_create.TestCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
