# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.product_type import ProductType  # noqa: E501
from djclient.rest import ApiException


class TestProductType(unittest.TestCase):
    """ProductType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductType(self):
        """Test ProductType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.product_type.ProductType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
