# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.finding_image import FindingImage  # noqa: E501
from djclient.rest import ApiException


class TestFindingImage(unittest.TestCase):
    """FindingImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindingImage(self):
        """Test FindingImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.finding_image.FindingImage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
