# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import djclient
from djclient.models.inline_response2003 import InlineResponse2003  # noqa: E501
from djclient.rest import ApiException


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = djclient.models.inline_response2003.InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
